---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accounts
    spec:
      containers:
      - image: us.icr.io/sn-labs-jeffreyjrv/accounts:1
        name: accounts
        resources: {}


        env:
          - name: DATABASE_HOST
            value: postgresql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: sampledb
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: pSaoeGMibFFvWCTk
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: user8RP

status: {}
